services:
  - type: web
    name: image-generation-huggingface
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_API_KEY
        sync: false
      - key: HF_API_TTI_BASE
        sync: false
      - key: PORT
        value: 8080
